[General]
alwaysShowChangelog = false
autoUpdate = false
BGMvolume = 50
checkCompatibilityOnStartup = false
chooseHomeTab = "General"
compatibilityEnabled = false
defaultControllerID = ""
enableDiscordRPC = false
fontsPath = ""
isConnectedToNetwork = false
isDevKit = false
isIdenticalLogGrouped = true
isPS4Pro = false
isPSNSignedIn = false
isTrophyPopupDisabled = false
logFilter = ""
logType = "sync"
playBGM = false
showSplash = false
sideTrophy = "right"
sysModulesPath = "D:/Tools/Emulators/shadPS4/sys_modules"
trophyNotificationDuration = 6.0
updateChannel = ""
userName = "zero"
volumeSlider = 100

[Input]
backButtonBehavior = "left"
backgroundControllerInput = false
cursorHideTimeout = 0
cursorState = 0
isMotionControlsEnabled = true
specialPadClass = 1
usbDeviceBackend = 0
useSpecialPad = false
useUnifiedInputConfig = true

[Audio]
mainOutputDevice = "Default Device"
micDevice = "Default Device"
padSpkOutputDevice = "Default Device"

[GPU]
allowHDR = false
copyGPUBuffers = false
directMemoryAccess = false
dumpShaders = false
fsrEnabled = false
Fullscreen = false
FullscreenMode = "Windowed"
internalScreenHeight = 720
internalScreenWidth = 1280
nullGpu = false
patchShaders = true
presentMode = "Mailbox"
rcasAttenuation = 250
rcasEnabled = false
readbackLinearImages = false
readbacks = false
readbacksMode = 0
screenHeight = 720
screenWidth = 1280
vblankDivider = 1
vblankFrequency = 60

[Vulkan]
crashDiagnostic = false
gpuId = 0
guestMarkers = false
hostMarkers = false
pipelineCacheArchive = false
pipelineCacheEnable = false
rdocEnable = false
validation = false
validation_core = true
validation_gpu = false
validation_sync = false

[Debug]
CollectShader = false
ConfigVersion = "92bdc40eef82a7a3ee241c35ba961d11a902dd8e"
DebugDump = false
FPSColor = true
isSeparateLogFilesEnabled = false
logEnabled = true
showFpsCounter = false

[Keys]
TrophyKey = ""

[GUI]
addonInstallDir = "D:/Tools/Emulators/shadPS4/addcont"
backgroundImageOpacity = 50
elfDirs = []
emulatorLanguage = "en_US"
gameTableMode = 0
geometry_h = 520
geometry_w = 861
geometry_x = 78
geometry_y = 192
iconSize = 36
iconSizeGrid = 69
installDirs = ["D:/Tools/Emulators/shadPS4/games"]
installDirsEnabled = [true]
loadGameSizeEnabled = true
mw_height = 520
mw_width = 861
pkgDirs = []
recentFiles = []
saveDataPath = "D:/Tools/Emulators/shadPS4/savedata"
showBackgroundImage = true
sliderPos = 0
sliderPosGrid = 0
theme = 0

[Settings]
consoleLanguage = 11

