BCAS20024: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Uncharted Drake's Fortune [BCAS20024]/
BCAS20071: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Demon's Souls [BCAS20071]/
BCAS20097: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Uncharted 2 Among Thieves [BCAS20097]/
BCAS20224: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/FINAL FANTASY XIII-2 [BCAS20224]/
BCAS20270: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/The Last of Us [BCAS20270]/
BCAS20279: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/LIGHTNING RETURNS FINAL FANTASY XIII [BCAS20279]/
BCAS25003: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/God of War III [BCAS25003]/
BCAS25005: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/FINAL FANTASY XIII [BCAS25005]/
BCAS25014: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Uncharted 3 Drake's DeceptionGame of the Year [BCAS25014]/
BLAS50528: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/DARK SOULS PREPARE TO DIE EDITION [BLAS50528]/
BLAS50785: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/DARK SOULS II Scholar of the First Sin [BLAS50785]/
BLAS50815: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/METAL GEAR SOLID V THE PHANTOM PAIN(CHN,KOR) [ BLAS50815]/
BLJM60223: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/NieR Replicant [BLJM60223]/
BLUS30092: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Devil May Cry 4 [BLUS30092]/
BLUS30169: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Silent Hill Homecoming [BLUS30169]/
BLUS30565: D:/Tools/ROMs/Sony - Playstation 3/Likes PS3 ROMs/DIR/Silent Hill Downpour [BLUS30565]/